image: jumpingrivers/base-image

# Values should be 0, unless reason given
variables:
  SPACE: 10
  NO_SPACE:10
  COMMENT: 10 # A comment

# Install jrIdentity from other repo
before_script:
  - Rscript -e "install.packages('inteRgrate')"

check:
  script:
    - Rscript -e "inteRgrate::check_pkg()"
  except:
    - tags
